Feature/point cloud to 2 d map converter
knmlprz/TrailblazerML pull request #17
Opened 2024-06-02 15:31 UTC by Sygnator

close #1 

dodano:
- odczyt z chmury punktów, 
- konwersję chmury punktów na mapę 2D, 
- symulacje mapy 2D w czasie rzeczywistym.

2024-06-02 17:57 UTC, FWalkowicz requested changes

2024-06-02 17:57 UTC, FWalkowicz commented on src/map2d/translator.py
> +    def point_cloud_to_2d_map(self, point_cloud, accel_position=(0, 0, 0)):
Możesz dodać opisy metod oraz typowanie?

2024-06-02 17:57 UTC, FWalkowicz commented on src/map2d/translator.py
> +    def generate_random_point_cloud(self, num_points=1000, value_range=(-1, 1)):
Możesz usunąć niepotrzebne funkcje.

2024-06-02 17:57 UTC, FWalkowicz commented on src/map2d/translator.py
> +        for i in range(height):
Zastanawiałeś się czy nie było by dla nas lepiej iterować tylko po niepustych pixelach? Teraz lecisz po całej tablicy `self.map_2d` można by tu zoptymalizować kod i zmniejszyć liczbę operacji. Coś w tym stylu:
```python
 non_nan_index = np.where(~np.isnan(self.map_2d))
 for i, j in zip(non_nan_indices[0], non_nan_indices[1]):
        z = self.map_2d[i, j]
        x = i / height
        y = j / width
        points.append([x, y, z])
        colors.append([z, z, z])
```

2024-06-03 15:44 UTC, Kleczyk commented on src/main.py
> +    # Wczytaj przykładową chmurę punktów
issue PR robimy piszemy po polsku ale kod zostawmy tylko po angielsku

2024-06-03 15:44 UTC, Kleczyk commented on src/vision/QAK/reading_data.py
> +        vis.destroy_window()
jak mergowałś z mojego brancha to to nie push'uj tych zmian z swojego bo będziemy mieli konflikty zrób sobie `git rm -r --cached <file>`

2024-06-03 15:44 UTC, Kleczyk commented on src/vision/QAK/transform_data.py
> +    pass
jak mergowałś z mojego brancha to to nie push'uj tych zmian z swojego bo będziemy mieli konflikty zrób sobie `git rm -r --cached <file>`

2024-06-03 15:44 UTC, Kleczyk commented on pyproject.toml
> +pillow = "^10.3.0"
jeśli już nie będziemy operować na .jpg chyba nie potrzebujemy pillow

2024-06-04 20:52 UTC, Sygnator commented on src/map2d/translator.py
> +        for i in range(height):
done

2024-06-04 20:52 UTC, Sygnator commented on src/main.py
> +    # Wczytaj przykładową chmurę punktów
done

2024-06-05 00:23 UTC, DamianKobylinski commented
Potrzebuje w pełni sprawdzonego simulation_loopa
- [x] algorytm A* zaimplementowany - działa dla gotowej całej mapy
- [ ] implementacja co cykl

Muszę teraz zaimplementować to co cykl -> kiedy @Sygnator dasz radę wdrożyć poprawki?

2024-06-05 08:56 UTC, Kleczyk approved these changes

2024-06-06 18:13 UTC, FWalkowicz approved these changes
lgtm

2024-06-06 18:14 UTC, merged