Cropped map to global 2d map
knmlprz/TrailblazerML pull request #48
Opened 2024-07-07 14:06 UTC by Sygnator

Update global 2d map.

2024-07-07 17:56 UTC, Kleczyk requested changes
małe zmianki  tak to git

2024-07-07 17:56 UTC, Kleczyk commented on src/map2d/translator.py
> +        for i in range(p_height):
for  nie są zbyt optymalnym rozwiązaniem bo robimy to element po elemencie 
```python
zeros = np.zeros((5000, 5000))
global_map = zeros
small_matrix = np.random.rand(1000, 1000)  

start_row = 3434
start_col = 2344

global_map[start_row:start_row + small_matrix.shape[0], start_col:start_col + small_matrix.shape[1]] += small_matrix

```
to jest lepsze podejście bo wszytko się dzieje w numpy i nie są alokowane dodatkowe macierze na czas przepisania

2024-07-07 17:56 UTC, Kleczyk commented on src/map2d/translator.py
>      def point_cloud_to_2d_map(self, point_cloud, accel_position=(0, 0, 0)):
popraw mnie jeśli się mylę ale tego chyba nie potrzebujemy już ?

2024-07-08 07:25 UTC, FWalkowicz approved these changes
lgtm

2024-07-08 11:10 UTC, Kleczyk approved these changes
LGTM

2024-07-08 11:14 UTC, merged