Feature/korekcja celu
knmlprz/TrailblazerML pull request #63
Opened 2024-07-12 08:41 UTC by FWalkowicz

2024-07-13 17:37 UTC, kosiarn requested changes
Jeszcze dwie uwagi do kodu spoza pull requesta:

- `src/vision/qrcode/qr_code_map_correction.py` - w funkcji `newDestination()` type hint parametru `detected_markers` zdaje się być niepoprawny(z kodu na samym dole wynika że funkcja spodziewa się listy słowników),
- bloku `if "__name__" == "__main__"` nie trzeba wykomentowywać - i tak wykona się tylko po bezpośrednim uruchomieniu skryptu.

2024-07-13 17:37 UTC, kosiarn commented on src/algorithm/navigation_algorithm.py
> +    def a_star_search(self) -> list:
```suggestion
    def a_star_search(self) -> list[tuple]:
```

w zależności od użytej wersji Pythona (>= 3.10.14) powinno działać bez zarzutu

2024-07-13 17:37 UTC, kosiarn commented on src/main.py
> +    end_goal = (point_cloud_mapper.res - 3, point_cloud_mapper.res - 2)
magiczne liczby

2024-07-13 17:37 UTC, kosiarn commented on src/vision/qrcode/qr_code_map_correction.py
>  def load_config_sectors(config_path: str = "/home/filip/PycharmProjects/TrailblazerML/src/utils/sectors_conf.json") -> dict:
ścieżka zależna od użytego komputera, powinna być zaciągana ze skryptu konfiguracyjnego/pliku .env

2024-07-13 17:37 UTC, kosiarn commented on src/vision/qrcode/qr_code_map_correction.py
>              }
czy tu da radę złożyć to w jedną pętlę? obecnie złożoność jest $O(n^2)$

2024-07-17 11:48 UTC, Kleczyk approved these changes
LGTM

2024-07-17 11:48 UTC, merged